



<HTML><HEAD>

<TITLE>December 1997/Error Handling with C++ Exceptions, Part 2/Listing 1</TITLE></HEAD>
<BODY BACKGROUND="" BGCOLOR="#FFFFFF" TEXT="#000000">
<h4>Listing 1:	Illustrates a dangling resource</h4>

<pre>
// destroy3.cpp
#include &lt;stdio.h&gt;

main()
{
    void f(const char*);
    try
    {
        f("destroy3.cpp");
    }
    catch(int)
    {
        puts("Caught exception");
    }
}

void f(const char* fname)
{
    FILE* fp = fopen(fname,"r");
    if (fp)
    {
        throw 1;
        fclose(fp);     // This won't happen
    }
}

// Output:
Caught exception
//End of File
</pre>
</body></html>
