



<HTML><HEAD>

<TITLE>November 1997/Error Handling with C++ Exceptions, Part 1/Listing 5</TITLE></HEAD>
<BODY BACKGROUND="" BGCOLOR="#FFFFFF" TEXT="#000000">
<h4>Listing 5:	Illustrates stack unwinding</h4>

<pre>
// destroy2.cpp
#include &lt;iostream&gt;
using namespace std;

class Foo
{
public:
    Foo() {cout &lt;&lt; "Foo constructor" &lt;&lt; endl;}
    ~Foo() {cout &lt;&lt; "Foo destructor" &lt;&lt; endl;}
};

main()
{
    void f();
    try       // Turn on exception handling
    {
        f();
    }
    catch(int)
    {
        cout &lt;&lt; "Caught exception" &lt;&lt; endl;
    }
    return 0;
}

void f()
{
    void g();
    Foo x;
    g();
}

void g()
{
    Foo x;
    throw 1;
}

// Output:
Foo constructor
Foo constructor
Foo destructor
Foo destructor
Caught exception
//End of File
</pre>
</body></html>
